project:
  type: website

website:
  title: "HM Revenue and Customs"
  navbar:
    logo: images/hmrc-logo.png
    left:
      - href: index.qmd
        text: Home
      - href: demo1-pie-chart.qmd
        text: Demo 1 - Pie Chart
      - href: requirements.qmd
        text: Requirements

format:
  html:
    toc: true
    css: styles.css   # Add this line to include your custom stylesheet

execute:
  enabled: true
  echo: true
