project:
  type: website

website:
  title: "GDS + Quarto Demo"
  navbar: false   # we'll use GOV.UK header styles instead of Quarto's navbar

# Global HTML settings
lang: en-GB

format:
  html:
    theme: none            # disable Bootstrap so it won't clash with GOV.UK styles
    toc: false
    page-layout: full      # let GOV.UK's container control the page width
    include-in-header:
      - gds-header.html    # loads GOV.UK Frontend CSS/JS and init script
    body-attrs: 'class="govuk-template__body"'
