project:
  type: website

website:
  title: "GDS + Quarto Demo"
  navbar: false

lang: en-GB

format:
  html:
    theme: none
    toc: false
    page-layout: full
    include-in-header:
      - gds-header.html
    include-before-body:
      - govuk-wrapper-start.html
    include-after-body:
      - govuk-wrapper-end.html
    body-attrs: 'class="govuk-template__body"'
