project:
  type: website

website:
  title: "My Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: demo1-pie-chart.qmd
        text: Pie Chart

format:
  html:
    include-in-header: gds-header.html
