project:
  type: website

website:
  title: "HM Revenue and Customs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: demo1-pie-chart.qmd
        text: Demo 1 - Pie Chart

format:
  html:
    toc: true
    include-in-header: gds-header.html

execute:
  echo: false
