project:
  type: website

website:
  title: "Python and Posit Practice Channel"

format:
  html:
    theme: none
    page-layout: full
    include-in-header: includes/gds-header.html
    include-before-body: includes/gds-wrapper-start.html
    include-after-body: includes/gds-wrapper-end.html
    body-attrs: 'class="govuk-template__body"'
    css: styles/govuk-frontend-5.11.1.min.css