project:
  type: website

website:
  title: "My Site"

format:
  html:
    theme: none
    page-layout: full
    include-in-header: gds-header.html
    include-before-body: gds-wrapper-start.html
    include-after-body: gds-wrapper-end.html
    body-attrs: 'class="govuk-template__body"'
