project:
  type: website

website:
  title: "My Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: demo1-pie-chart.qmd
        text: Pie Chart

format:
  html:
    theme: none
    page-layout: full
    include-in-header: gds-header.html
    include-before-body: gds-wrapper-start.html
    include-after-body: gds-wrapper-end.html
    body-attrs: 'class="govuk-template__body"'
